version: "3.9"

services:
  db:
    build:
      context: ./Service-A
      dockerfile: Dockerfile.postgres
    container_name: lunchbox-db
    environment:
      POSTGRES_DB: lunchboxdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lunchnet

  service-a:
    build:
      context: ./Service-A
    container_name: lunchbox-api
    env_file:
      - ./Service-A/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - service-c
    networks:
      - lunchnet

  service-c:
    build:
      context: ./Service-C
    container_name: lunchbox-recommender
    ports:
      - "3000:3000"
    networks:
      - lunchnet

volumes:
  pgdata:

networks:
  lunchnet:


# to start already existing containers:
# docker-compose start

# to stop: 
# docker-compose stop

# to run:
# docker-compose up --build
# docker-compose up -d

# to create images and run:
# docker-compose up

# same, but in detached mode:
# docker-compose up -d

# awlays creates a new images:
# docker-compose up --build

# just builds without running
# docker-compose build

